apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hello-ns
  labels:
    app: hello
spec:
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
  type: NodePort
  selector:
    app: hello
